window.jsonPayload = {
    "registration" : {
        "activationMachineInfo" : {
            "lockingDetail" : [],
            "customProperty" : [],
            "machineID" : null,
            "machineName" : "%22%7d%3bprompt%28%29%3b%7b%0a%0d%2f%2fwhscheck",
            "statusCode" : null,
            "server1" : null,
            "server2" : null,
            "server3" : null,
            "server4" : null,
            "server5" : null,
            "server6" : null,
            "deploymentCode" : null,
            "platformCode" : null,
            "languageCode" : null,
            "productNum" : null
        },
        "rehostFromMachineInfo" : null,
        "customProperty" : [],
        "activationEntitlement" : [],
        "item" : [ {
            "poeticInternalID" : "9659285",
            "quantity" : 1
        } ],
        "component" : [],
        "partner" : [ {
            "billToDetail" : null,
            "shipToDetail" : null,
            "address" : null,
            "customProperty" : [],
            "contact" : [],
            "phone" : null,
            "role" : "EndCo",
            "companyTypeCode" : null,
            "name" : null,
            "altName" : null,
            "act" : "Update",
            "poeticInternalID" : null,
            "publisherID" : "G085386522",
            "oneTime" : null,
            "createdByPartnerInternalID" : null,
            "createdByPartnerPublisherID" : null,
            "transactionCode" : null,
            "domainName" : null
        } ],
        "notes" : [ {
            "value" : null,
            "typeCode" : null,
            "relatedID" : null,
            "usageType" : "EXTERNAL"
        } ],
        "registerLAC" : "",
        "registerProductNum" : null,
        "registerProductLine" : null,
        "quantity" : null,
        "type" : "Permanent",
        "mode" : "Validation",
        "certFormat" : null,
        "emailCertTo" : null,
        "programCode" : null,
        "contractNum" : null,
        "contractStartDate" : null,
        "contractEndDate" : null,
        "activationActionCode" : null,
        "isIncrementalKey" : "F",
        "doNotAutoSendCertificate" : "F",
        "usePendingEntitlements" : "F",
        "allowPartialActivation" : "T",
        "useQtyCalculator" : "F",
        "moveAll" : "F",
        "overrideReturnRestrictionsCode" : null,
        "disableMachine" : "F",
        "overrideTargetTagValidation" : "F"
    }
};